""" bledpov_ui.py --

 UI generated by GUI Builder Build 146 on 2008-06-27 02:36:11 from:
    /home/lameiro/python/bledpov/bledpov.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Bledpov(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self.serial_listbox = Tkinter.Listbox(root,
            height = 5,
            width = 0,
        )
        self.b_scan = Tkinter.Button(root,
            text = "scan",
        )
        self._label_1 = Tkinter.Label(root,
            text = "Select the port to use",
        )
        self._label_2 = Tkinter.Label(root,
            text = "Choose the command to send",
        )
        self.serial_scrollbar = Tkinter.Scrollbar(root,
        )
        self.send_cmd1 = Tkinter.Button(root,
            text = "Dummy Command",
        )
        self.send_cmd2 = Tkinter.Button(root,
            text = "Firmware Version",
        )
        self.send_cmd3 = Tkinter.Button(root,
            text = "LEDs Test",
        )
        self.send_cmd4 = Tkinter.Button(root,
            text = "Test Sensor",
        )
        self._spinbox_1 = Tkinter.Spinbox(root,
            borderwidth = 1,
            disabledbackground = "#ffffff",
            justify = "center",
            state = "readonly",
            values = "1 2 3 4 5 6 7 8",
            width = 10,
        )
        self.menu = Tkinter.Menu(root,
        )

        # widget commands

        self.serial_listbox.configure(
            xscrollcommand = self.serial_listbox_xscrollcommand
        )
        self.serial_listbox.configure(
            yscrollcommand = self.serial_scrollbar.set
        )
        self.b_scan.configure(
            command = self.b_scan_command
        )
        self.serial_scrollbar.configure(
            command = self.serial_listbox.yview
        )
        self.send_cmd1.configure(
            command = self.send_cmd1_command
        )
        self.send_cmd2.configure(
            command = self.send_cmd2_command
        )
        self.send_cmd3.configure(
            command = self.send_cmd3_command
        )
        self.send_cmd4.configure(
            command = self.send_cmd4_command
        )
        self._spinbox_1.configure(
            command = self._spinbox_1_command
        )
        self._spinbox_1.configure(
            invalidcommand = self._spinbox_1_invalidcommand
        )
        self._spinbox_1.configure(
            validatecommand = self._spinbox_1_validatecommand
        )
        self._spinbox_1.configure(
            xscrollcommand = self._spinbox_1_xscrollcommand
        )
        self.menuitem1 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "File",
            menu = self.menuitem1,
        )
        self.menuitem1.add_command(
            command = exit,
            label = "Exit",
        )


        # Geometry Management
        self.serial_listbox.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.b_scan.grid(
            in_    = root,
            column = 6,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_1.grid(
            in_    = root,
            column = 3,
            row    = 1,
            columnspan = 3,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self._label_2.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 6,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "sew"
        )
        self.serial_scrollbar.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self.send_cmd1.grid(
            in_    = root,
            column = 1,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.send_cmd2.grid(
            in_    = root,
            column = 2,
            row    = 3,
            columnspan = 3,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.send_cmd3.grid(
            in_    = root,
            column = 5,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.send_cmd4.grid(
            in_    = root,
            column = 6,
            row    = 3,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._spinbox_1.grid(
            in_    = root,
            column = 5,
            row    = 4,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 57, pad = 0)
        root.grid_rowconfigure(2, weight = 1, minsize = 14, pad = 0)
        root.grid_rowconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(4, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 74, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 2, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 40, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 62, pad = 0)
        root.grid_columnconfigure(5, weight = 0, minsize = 112, pad = 0)
        root.grid_columnconfigure(6, weight = 0, minsize = 40, pad = 0)
        root.configure(menu = self.menu)


