""" bledpov_ui.py --

 UI generated by GUI Builder Build 146 on 2008-06-26 23:41:06 from:
    /home/lameiro/python/bledpov/bledpov.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Bledpov(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self.serial_listbox = Tkinter.Listbox(root,
            height = 5,
            width = 0,
        )
        self.b_scan = Tkinter.Button(root,
            text = "scan",
        )
        self._label_1 = Tkinter.Label(root,
            text = "Select the port to use",
        )
        self.cmd_listbox = Tkinter.Listbox(root,
            height = 0,
            width = 0,
        )
        self.b_send = Tkinter.Button(root,
            text = "send command",
        )
        self._label_2 = Tkinter.Label(root,
            text = "Choose the command to send",
        )
        self.serial_scrollbar = Tkinter.Scrollbar(root,
        )
        self.cmd_scrollbar = Tkinter.Scrollbar(root,
        )
        self.menu = Tkinter.Menu(root,
        )

        # widget commands

        self.serial_listbox.configure(
            xscrollcommand = self.serial_listbox_xscrollcommand
        )
        self.serial_listbox.configure(
            yscrollcommand = self.serial_scrollbar.set
        )
        self.b_scan.configure(
            command = self.b_scan_command
        )
        self.cmd_listbox.configure(
            xscrollcommand = self.cmd_listbox_xscrollcommand
        )
        self.cmd_listbox.configure(
            yscrollcommand = self.cmd_scrollbar.set
        )
        self.b_send.configure(
            command = self.b_send_command
        )
        self.serial_scrollbar.configure(
            command = self.serial_listbox.yview
        )
        self.cmd_scrollbar.configure(
            command = self.cmd_listbox.yview
        )
        self.menuitem1 = Tkinter.Menu(self.menu,
            tearoff = 0,
        )
        self.menu.add_cascade(
            label = "File",
            menu = self.menuitem1,
        )
        self.menuitem1.add_command(
            command = exit,
            label = "Exit",
        )


        # Geometry Management
        self.serial_listbox.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.b_scan.grid(
            in_    = root,
            column = 4,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_1.grid(
            in_    = root,
            column = 3,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.cmd_listbox.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self.b_send.grid(
            in_    = root,
            column = 4,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._label_2.grid(
            in_    = root,
            column = 3,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self.serial_scrollbar.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )
        self.cmd_scrollbar.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "nsew"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 91, pad = 0)
        root.grid_rowconfigure(2, weight = 1, minsize = 73, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 165, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 8, pad = 0)
        root.grid_columnconfigure(3, weight = 0, minsize = 332, pad = 0)
        root.grid_columnconfigure(4, weight = 0, minsize = 40, pad = 0)
        root.configure(menu = self.menu)


