#!/usr/bin/env python
#		Copyright (C) Ricardo Lameiro 2008
#		Bicicleledpov.py v 0.01 - transfer and control of the hardware via Serial port
#       
#       This program uses the pyserial module tha can be used in Windows and 
#       *nixes OSes. You can download this module at 
#       http://pyserial.sourceforge.net/
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2 of the License, or
#       (at your option) any later version.
#       
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#       
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, write to the Free Software
#       Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#       MA 02110-1301, USA.

""" bledpov.py --

 UI generated by GUI Builder Build 146 on 2008-06-26 23:41:08 from:
    /home/lameiro/python/bledpov/bledpov.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from bledpov_ui import Bledpov

# BEGIN USER CODE global
import serial



def scan():
    """scan for available ports. return a list of tuples (num, name)"""
    available = []
    for i in range(256):
        try:
            s = serial.Serial(i)
            available.append( (i, s.portstr))
            s.close()   
        except serial.SerialException:
            pass
    return available

ports = scan()
# END USER CODE global

class CustomBledpov(Bledpov):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # b_scan_command --
    #
    # Callback to handle b_scan widget option -command
    def b_scan_command(self, *args):
    	
        self.serial_listbox.delete(0, END) # this delete all items on the listbox (refresh)
        
        # A loop that inserts the diferent serial port avaiable into the serial_listbox
        
        for item in ports:
    		self.serial_listbox.insert(END, item)
    	# A loop that inserts the diferent commands into the cmd_listbox
    	
    	
        self.cmd_listbox.delete(0, END) # this delete all items on the listbox (refresh)
        
    	for item in ['Command 0', 'Command 1', 'Command 2', 'Command 3', 'Command 4']:
			    self.cmd_listbox.insert(END, item)

    # b_send_command --
    #
    # Callback to handle b_send widget option -command
    def b_send_command(self, *args):
        pass

    # cmd_listbox_xscrollcommand --
    #
    # Callback to handle cmd_listbox widget option -xscrollcommand
    def cmd_listbox_xscrollcommand(self, *args):
        pass

    # serial_listbox_xscrollcommand --
    #
    # Callback to handle serial_listbox widget option -xscrollcommand
    def serial_listbox_xscrollcommand(self, *args):
        pass

    # _button_1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _button_1_command(self, *args):
        pass

    # _button_2_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _button_2_command(self, *args):
        pass

    # _listbox_2_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _listbox_2_xscrollcommand(self, *args):
        pass

    # _listbox_2_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _listbox_2_yscrollcommand(self, *args):
        pass

    # _scrollbar_1_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _scrollbar_1_command(self, *args):
        pass

    # _scrollbar_2_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def _scrollbar_2_command(self, *args):
        pass

    # cmd_listbox_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def cmd_listbox_yscrollcommand(self, *args):
        pass

    # cmd_scrollbar_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def cmd_scrollbar_command(self, *args):
        pass

    # serial_listbox_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def serial_listbox_yscrollcommand(self, *args):
        pass

    # serial_scrollbar_command --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def serial_scrollbar_command(self, *args):
		pass

    # seriallistbox_xscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def seriallistbox_xscrollcommand(self, *args):
        pass

    # seriallistbox_yscrollcommand --
    #
    # Legacy command found in callback code. Add user comments inside body.
    def seriallistbox_yscrollcommand(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomBledpov(root)
    root.title('bledpov')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
